create_clock -period 10.0 [get_ports i_clk]

set_property PACKAGE_PIN R4 [get_ports i_clk] 
set_property PACKAGE_PIN U7 [get_ports i_rstn] 

set_property PACKAGE_PIN Y18 [get_ports LED[0]]
set_property PACKAGE_PIN AA18 [get_ports LED[1]]
set_property PACKAGE_PIN AB18 [get_ports LED[2]]
set_property PACKAGE_PIN W19 [get_ports LED[3]]
set_property PACKAGE_PIN Y19 [get_ports LED[4]]
set_property PACKAGE_PIN AA19 [get_ports LED[5]]
set_property PACKAGE_PIN W20 [get_ports LED[6]]
set_property PACKAGE_PIN AA20 [get_ports LED[7]]
set_property PACKAGE_PIN AB20 [get_ports LED[8]]
set_property PACKAGE_PIN W21 [get_ports LED[9]]
set_property PACKAGE_PIN Y21 [get_ports LED[10]]
set_property PACKAGE_PIN AA21 [get_ports LED[11]]
set_property PACKAGE_PIN AB21 [get_ports LED[12]]
set_property PACKAGE_PIN W22 [get_ports LED[13]]
set_property PACKAGE_PIN Y22 [get_ports LED[14]]
set_property PACKAGE_PIN AB22 [get_ports LED[15]]

set_property IOSTANDARD LVCMOS33 [get_ports i_clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_rstn]

set_property IOSTANDARD LVCMOS33 [get_ports LED[0]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[1]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[2]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[3]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[4]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[5]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[6]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[7]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[8]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[9]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[10]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[11]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[12]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[13]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[14]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[15]]



